# Generated by Django 3.2.16 on 2024-02-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brachRdept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='qulificationrfeild',
            old_name='name',
            new_name='Qulification',
        ),
        migrations.CreateModel(
            name='careerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=50)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brachRdept', to='career.brachrdept')),
            ],
        ),
        migrations.AddField(
            model_name='brachrdept',
            name='Qulification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qulificationRfeild', to='career.qulificationrfeild'),
        ),
    ]
