# Generated by Django 3.2.16 on 2024-02-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20240221_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerdetails',
            name='Department',
        ),
        migrations.DeleteModel(
            name='brachRdept',
        ),
        migrations.DeleteModel(
            name='careerdetails',
        ),
        migrations.DeleteModel(
            name='qulificationRfeild',
        ),
    ]
