# Generated by Django 3.2.16 on 2024-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0003_auto_20240221_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='qulificationRfeild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qulification', models.CharField(max_length=50)),
            ],
        ),
    ]
