# Generated by Django 3.2.16 on 2024-02-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_qulificationrfeild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.qulificationrfeild')),
            ],
        ),
    ]
