# Generated by Django 3.2.16 on 2024-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_qulificationrfeild_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='duriations',
            field=models.CharField(default='', max_length=500),
        ),
    ]
