# Generated by Django 3.2.16 on 2024-02-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_auto_20240221_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='branch',
            new_name='branch_name',
        ),
    ]
